import type { ProductionData } from './types';

/**
 * 制作工坊种子数据（按 projectId 隔离）
 *
 * p1「山海志异」为完整演示数据，p2/p3 为精简数据。
 * 数据与 db.ts 中的任务/资产库语义保持一致，方便演示联动。
 */

export type ProductionDB = Record<string, ProductionData>;

export function seedProduction(): ProductionDB {
  return {
    p1: {
      scripts: [
        {
          id: 's1',
          projectId: 'p1',
          name: '《山海志异》第二幕修订稿',
          versionNo: 3,
          createTime: '2026-08-28',
          acts: [
            {
              id: 'act-1',
              name: '第一幕',
              scenes: [
                {
                  id: 'script-text-1',
                  title: '内景·白泽堂 - 晨',
                  paragraphs: [
                    '白小满伏在案前醒来，肩头白鹿纹微微发亮。',
                    '师尊：纸刃认主，你便是下一任守境人。',
                    '白小满：可是徒儿连一只妖都没收服过。',
                    '师尊把一枚泛青的纸刃放入她掌心。',
                  ],
                },
                {
                  id: 'script-text-2',
                  title: '外景·白泽堂山门',
                  paragraphs: [
                    '山雾未散，白小满背着行囊走下石阶。',
                    '风起，纸刃在她袖中轻轻震颤。',
                    '白小满：去阴阳集市，找那只逃走的萤络。',
                  ],
                },
              ],
            },
            {
              id: 'act-2',
              name: '第二幕',
              scenes: [
                {
                  id: 'script-text-3',
                  title: '外景·阴阳集市 - 昼',
                  paragraphs: [
                    '阴阳集市人声鼎沸，半人半妖的摊主沿街叫卖。',
                    '白小满穿梭其间，纸刃指向一处挂满青灯的铺子。',
                    '摊主：客人要寻的东西，在荒墟渡口。',
                  ],
                },
                {
                  id: 'script-text-4',
                  title: '外景·荒墟渡口 - 黄昏',
                  paragraphs: [
                    '渡口残阳如血，水面浮着零星的纸灯。',
                    '萤络的妖火在芦苇间忽明忽暗。',
                    '白小满抽出纸刃，刀锋映出一双琥珀色的眼睛。',
                    '萤络：守境人？你看起来，还不够格。',
                  ],
                },
                {
                  id: 'script-text-5',
                  title: '内景·画舫 - 夜',
                  paragraphs: [
                    '画舫顺水而行，舫内烛影摇动。',
                    '萤络倚在窗边，指尖捻着一簇幽绿的火。',
                    '白小满：放下妖火，我不伤你。',
                    '萤络：你连它是怎么来的都不知道，谈何收服。',
                  ],
                },
              ],
            },
          ],
        },
      ],
      scenes: [
        {
          id: 'SC-001',
          projectId: 'p1',
          sceneNo: 'SC-001',
          name: '阴阳集市·白小满初入',
          type: '外景·昼戏',
          duration: '0:24',
          status: 'in_progress',
          riskLevel: 'medium',
          characters: ['白小满', '摊主'],
          location: '阴阳集市',
          schedule: '2026-09-02',
          complexity: 60,
          tasks: 3,
          assetsReady: 4,
          assetsTotal: 6,
          assigneeName: 'u-art',
        },
        {
          id: 'SC-002',
          projectId: 'p1',
          sceneNo: 'SC-002',
          name: '荒墟渡口·遭遇妖兽萤络',
          type: '外景·黄昏',
          duration: '0:32',
          status: 'draft',
          riskLevel: 'high',
          characters: ['白小满', '萤络'],
          location: '荒墟渡口',
          schedule: '2026-09-04',
          complexity: 82,
          tasks: 2,
          assetsReady: 1,
          assetsTotal: 5,
          assigneeName: 'u-video',
        },
        {
          id: 'SC-003',
          projectId: 'p1',
          sceneNo: 'SC-003',
          name: '画舫·纸刃初显',
          type: '内景·夜戏',
          duration: '0:28',
          status: 'scheduled',
          riskLevel: 'low',
          characters: ['白小满', '萤络'],
          location: '画舫',
          schedule: '2026-09-06',
          complexity: 45,
          tasks: 1,
          assetsReady: 2,
          assetsTotal: 4,
          assigneeName: 'u-art',
        },
      ],
      tasks: [
        {
          id: 'T-001',
          projectId: 'p1',
          sceneId: 'SC-001',
          code: 'T-001',
          stage: '美术关键帧',
          status: 'completed',
          responsible: 'u-art',
          department: '美术线',
          startTime: '09:00',
          endTime: '12:00',
          location: '美术组',
          progress: '100%',
          durationSec: 3600,
          description: '阴阳集市主镜头关键帧上色',
          dependencies: [],
          clipStartSec: 0,
          clipEndSec: 8.7,
          prompt: '阴阳集市主镜头关键帧，青灯纸伞错落，白小满立画面前景，国风厚涂',
          genModel: 'Seedream 3.0',
        },
        {
          id: 'T-002',
          projectId: 'p1',
          sceneId: 'SC-001',
          code: 'T-002',
          stage: '图生视频',
          status: 'in_progress',
          responsible: 'u-video',
          department: '视频线',
          startTime: '13:00',
          endTime: '17:00',
          location: '视频组',
          progress: '65%',
          durationSec: 7200,
          description: '集市穿梭镜头成片候选',
          dependencies: ['T-001'],
          clipStartSec: 8.7,
          clipEndSec: 17.4,
          prompt: '白小满穿行阴阳集市，镜头跟随前推，人群虚化，暖调黄昏光，5 秒',
          genModel: 'Kling 1.6',
        },
        {
          id: 'T-003',
          projectId: 'p1',
          sceneId: 'SC-001',
          code: 'T-003',
          stage: '精修合成',
          status: 'pending',
          responsible: 'u-post',
          department: '后期线',
          startTime: '17:30',
          endTime: '19:00',
          location: '后期组',
          progress: '0%',
          durationSec: 2700,
          description: '候选片段调色与首尾帧衔接',
          dependencies: ['T-002'],
          clipStartSec: 17.4,
          clipEndSec: 26.1,
        },
        {
          id: 'T-004',
          projectId: 'p1',
          sceneId: 'SC-002',
          code: 'T-004',
          stage: '美术关键帧',
          status: 'in_progress',
          responsible: 'u-art',
          department: '美术线',
          startTime: '09:00',
          endTime: '13:00',
          location: '美术组',
          progress: '40%',
          durationSec: 5400,
          description: '萤络妖火的质感关键帧',
          dependencies: [],
          clipStartSec: 26.1,
          clipEndSec: 34.8,
          prompt: '萤络妖火特写，幽绿火焰明灭，芦苇剪影，暗调高对比，国风奇幻',
          genModel: 'Flux 1.1 Pro',
        },
        {
          id: 'T-005',
          projectId: 'p1',
          sceneId: 'SC-002',
          code: 'T-005',
          stage: '图生视频',
          status: 'pending',
          responsible: 'u-video',
          department: '视频线',
          startTime: '14:00',
          endTime: '18:00',
          location: '视频组',
          progress: '0%',
          durationSec: 5400,
          description: '渡口对峙镜头生成',
          dependencies: ['T-004'],
          clipStartSec: 34.8,
          clipEndSec: 43.5,
          prompt: '荒墟渡口残阳对峙，白小满抽刀，萤络妖火浮动，镜头缓慢横移',
          genModel: 'Kling 1.6',
        },
        {
          id: 'T-006',
          projectId: 'p1',
          sceneId: 'SC-003',
          code: 'T-006',
          stage: '美术关键帧',
          status: 'pending',
          responsible: 'u-art',
          department: '美术线',
          startTime: '09:00',
          endTime: '12:00',
          location: '美术组',
          progress: '0%',
          durationSec: 3600,
          description: '画舫夜戏分镜关键帧',
          dependencies: [],
          clipStartSec: 43.5,
          clipEndSec: 52.2,
        },
      ],
      assets: [
        {
          id: 'DA-001',
          projectId: 'p1',
          name: '白小满 - 角色立绘',
          assetType: '角色资产',
          version: 'v1.3',
          status: '已发布',
          artist: 'u-art',
          size: '256MB',
          format: 'PNG',
          usedInScenes: ['SC-001', 'SC-002', 'SC-003'],
          qualityCheck: 'PASS',
        },
        {
          id: 'DA-002',
          projectId: 'p1',
          name: '妖兽·萤络 - 妖形态',
          assetType: '角色资产',
          version: 'v1.1',
          status: '制作中',
          artist: 'u-art',
          size: '198MB',
          format: 'PNG',
          usedInScenes: ['SC-002', 'SC-003'],
          qualityCheck: 'PENDING',
        },
        {
          id: 'DA-003',
          projectId: 'p1',
          name: '阴阳集市 - 场景概念',
          assetType: '场景资产',
          version: 'v2.0',
          status: '已发布',
          artist: 'u-art',
          size: '512MB',
          format: 'PSD',
          usedInScenes: ['SC-001'],
          qualityCheck: 'PASS',
        },
        {
          id: 'DA-004',
          projectId: 'p1',
          name: '荒墟渡口 - 场景概念',
          assetType: '场景资产',
          version: 'v0.9',
          status: '审核中',
          artist: 'u-art',
          size: '384MB',
          format: 'PSD',
          usedInScenes: ['SC-002'],
          qualityCheck: 'PENDING',
        },
        {
          id: 'DA-005',
          projectId: 'p1',
          name: '画舫夜戏 - 场景概念',
          assetType: '场景资产',
          version: 'v0.5',
          status: '草稿',
          artist: 'u-art',
          size: '320MB',
          format: 'PSD',
          usedInScenes: ['SC-003'],
          qualityCheck: 'PENDING',
        },
        {
          id: 'DA-006',
          projectId: 'p1',
          name: '纸刃 - 道具设定',
          assetType: '道具资产',
          version: 'v1.0',
          status: '已发布',
          artist: 'u-art',
          size: '32MB',
          format: 'PNG',
          usedInScenes: ['SC-003'],
          qualityCheck: 'PASS',
        },
        {
          id: 'DA-007',
          projectId: 'p1',
          name: '青灯 - 道具设定',
          assetType: '道具资产',
          version: 'v0.8',
          status: '制作中',
          artist: 'u-art',
          size: '18MB',
          format: 'PNG',
          usedInScenes: ['SC-001', 'SC-002'],
          qualityCheck: 'PENDING',
        },
      ],
    },
    p2: {
      scripts: [
        {
          id: 's2',
          projectId: 'p2',
          name: '《晨光·城市》广告脚本',
          versionNo: 1,
          createTime: '2026-07-30',
          acts: [
            {
              id: 'act-1',
              name: '全片',
              scenes: [
                {
                  id: 'script-text-c1',
                  title: '内景·办公室 - 晨',
                  paragraphs: [
                    '城市苏醒，一杯晨光咖啡滑入画面。',
                    '主角端起咖啡，窗外的城市开始流动。',
                  ],
                },
              ],
            },
          ],
        },
      ],
      scenes: [
        {
          id: 'SC-C01',
          projectId: 'p2',
          sceneNo: 'SC-C01',
          name: '产品特写·咖啡',
          type: '内景·晨',
          duration: '0:08',
          status: 'completed',
          riskLevel: 'low',
          characters: ['主角'],
          location: '办公室',
          schedule: '2026-08-20',
          complexity: 30,
          tasks: 1,
          assetsReady: 2,
          assetsTotal: 2,
          assigneeName: 'u-video',
        },
      ],
      tasks: [
        {
          id: 'T-C01',
          projectId: 'p2',
          sceneId: 'SC-C01',
          code: 'T-C01',
          stage: '图生视频',
          status: 'completed',
          responsible: 'u-video',
          department: '视频线',
          startTime: '10:00',
          endTime: '15:00',
          location: '视频组',
          progress: '100%',
          durationSec: 3600,
          description: '产品旋转与蒸汽粒子',
          dependencies: [],
        },
      ],
      assets: [
        {
          id: 'DA-C01',
          projectId: 'p2',
          name: '晨光咖啡杯 - 产品模型',
          assetType: '道具资产',
          version: 'v1.2',
          status: '已发布',
          artist: 'u-video',
          size: '64MB',
          format: 'FBX',
          usedInScenes: ['SC-C01'],
          qualityCheck: 'PASS',
        },
      ],
    },
    p3: {
      scripts: [],
      scenes: [],
      tasks: [],
      assets: [],
    },
  };
}